name: Build Windows
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - run: choco install innosetup
      - run: python -m pip install setuptools wheel
      - run: python -m pip install -r requirements.txt
      - working-directory: ./packaging
        run: ./windows.cmd
      - uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./packaging/dist/*
          retention-days: 1
