name: Build Releases
on: [workflow_dispatch]
jobs:
  BuildLinux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: python3 -m pip install -r requirements.txt
      - working-directory: ./packaging
        run: ./linux_source.sh --tar yes --deb yes
